# These are supported funding model platforms
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
github: cvzi
ko_fi: cuzicvzi
liberapay: cuzi
patreon: cuzi
custom:
    - https://buymeacoff.ee/cuzi
    - https://flattr.com/@cuzi/github/cvzi
    - https://bandcamp.com/cuzi/wishlist
