exclude_paths:
  - 'tests/**'
  - 'example/**'
engines:
  bandit:
    enabled: true
  duplication:
    enabled: false
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      # Disable "Continuation line unaligned for hanging indent"
      E131:
        enabled: false
      # Disable "Line too long"
      E501:
        enabled: false 
  radon:
    enabled: true
  sonar-python:
    enabled: true
    checks:
      # Disable  "Rename function to match the regular expression ^[a-z_][a-z0-9_]{2,}$"
      python:S1542:
        enabled: false
