dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - nightly
  - "pypy3.5"
# command to install dependencies
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install codacy-coverage
# command to run tests
script:
  - python setup.py test
  - pytest
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coverage run -a tests/test_small.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coverage run -a tests/test_full.py; fi
# must be last (coverage will not track an installed module)
  - python setup.py install 
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coverage xml; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then python-codacy-coverage -r coverage.xml; fi
