dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install nose
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install python-coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install codacy-coverage; fi
# command to run tests
script:
  - python setup.py test
  - pytest
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then coverage run -a tests/test_small.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then coverage run -a tests/test_full.py; fi
# must be last (coverage will not track an installed module)
  - python setup.py install 
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then coverage xml; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then python-codacy-coverage -r coverage.xml; fi
